# Generated by Django 5.0.4 on 2024-04-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_role_alter_user_phone_user_role'),
    ]

    operations = [
    ]
